spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  jwt:
    secret : ${jwt_secret}

  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}

logging:
  level:
    org.hibernate.SQL: info

custom:
  s3url : ${s3url}
